// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `IrObjetivo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____IrObjetivo_h__
#define ____IrObjetivo_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompIrObjetivo
{

class IrObjetivo;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompIrObjetivo::IrObjetivo>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompIrObjetivo::IrObjetivo*);

}

}

namespace RoboCompIrObjetivo
{

class IrObjetivo;
bool operator==(const IrObjetivo&, const IrObjetivo&);
bool operator<(const IrObjetivo&, const IrObjetivo&);
::Ice::Object* upCast(::RoboCompIrObjetivo::IrObjetivo*);
typedef ::IceInternal::Handle< ::RoboCompIrObjetivo::IrObjetivo> IrObjetivoPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompIrObjetivo::IrObjetivo> IrObjetivoPrx;
void __patch(IrObjetivoPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompIrObjetivo
{

class Callback_IrObjetivo_go_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_go_Base> Callback_IrObjetivo_goPtr;

class Callback_IrObjetivo_turn_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_turn_Base> Callback_IrObjetivo_turnPtr;

class Callback_IrObjetivo_stop_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_stop_Base> Callback_IrObjetivo_stopPtr;

class Callback_IrObjetivo_getDistancia_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_getDistancia_Base> Callback_IrObjetivo_getDistanciaPtr;

class Callback_IrObjetivo_esVisible_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_esVisible_Base> Callback_IrObjetivo_esVisiblePtr;

class Callback_IrObjetivo_cogerCaja_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_cogerCaja_Base> Callback_IrObjetivo_cogerCajaPtr;

class Callback_IrObjetivo_soltarCaja_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IrObjetivo_soltarCaja_Base> Callback_IrObjetivo_soltarCajaPtr;

}

namespace IceProxy
{

namespace RoboCompIrObjetivo
{

class IrObjetivo : virtual public ::IceProxy::Ice::Object
{
public:

    void go(::Ice::Float x, ::Ice::Float z)
    {
        go(x, z, 0);
    }
    void go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx)
    {
        go(x, z, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(x, z, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(x, z, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(x, z, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(x, z, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z)
    {
        return begin_go(x, z, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx)
    {
        return begin_go(x, z, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::RoboCompIrObjetivo::Callback_IrObjetivo_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(::Ice::Float x, ::Ice::Float z, const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(x, z, &__ctx, __del, __cookie);
    }

    void end_go(const ::Ice::AsyncResultPtr&);
    
private:

    void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void turn(::Ice::Float speed)
    {
        turn(speed, 0);
    }
    void turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        turn(speed, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed)
    {
        return begin_turn(speed, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        return begin_turn(speed, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::RoboCompIrObjetivo::Callback_IrObjetivo_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    void end_turn(const ::Ice::AsyncResultPtr&);
    
private:

    void turn(::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_turn(::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void stop()
    {
        stop(0);
    }
    void stop(const ::Ice::Context& __ctx)
    {
        stop(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_stop(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_stop(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_stop(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_stop()
    {
        return begin_stop(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx)
    {
        return begin_stop(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::RoboCompIrObjetivo::Callback_IrObjetivo_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_stopPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_stop(&__ctx, __del, __cookie);
    }

    void end_stop(const ::Ice::AsyncResultPtr&);
    
private:

    void stop(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_stop(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Float getDistancia()
    {
        return getDistancia(0);
    }
    ::Ice::Float getDistancia(const ::Ice::Context& __ctx)
    {
        return getDistancia(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getDistancia(const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getDistancia(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getDistancia(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getDistancia(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getDistancia(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getDistancia(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getDistancia(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getDistancia(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getDistancia(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Float)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Float)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
                ::Ice::Float __ret;
                try
                {
                    __ret = __proxy->end_getDistancia(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Float)> _response;
        };
        return begin_getDistancia(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getDistancia()
    {
        return begin_getDistancia(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDistancia(const ::Ice::Context& __ctx)
    {
        return begin_getDistancia(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDistancia(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDistancia(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDistancia(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDistancia(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDistancia(const ::RoboCompIrObjetivo::Callback_IrObjetivo_getDistanciaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDistancia(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDistancia(const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_getDistanciaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDistancia(&__ctx, __del, __cookie);
    }

    ::Ice::Float end_getDistancia(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Float getDistancia(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getDistancia(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool esVisible(::Ice::Int tag)
    {
        return esVisible(tag, 0);
    }
    bool esVisible(::Ice::Int tag, const ::Ice::Context& __ctx)
    {
        return esVisible(tag, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_esVisible(::Ice::Int tag, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_esVisible(tag, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_esVisible(::Ice::Int tag, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_esVisible(tag, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_esVisible(::Ice::Int tag, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_esVisible(tag, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_esVisible(::Ice::Int tag, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_esVisible(tag, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_esVisible(::Ice::Int tag, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_esVisible(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_esVisible(tag, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag)
    {
        return begin_esVisible(tag, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag, const ::Ice::Context& __ctx)
    {
        return begin_esVisible(tag, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_esVisible(tag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_esVisible(tag, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag, const ::RoboCompIrObjetivo::Callback_IrObjetivo_esVisiblePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_esVisible(tag, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int tag, const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_esVisiblePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_esVisible(tag, &__ctx, __del, __cookie);
    }

    bool end_esVisible(const ::Ice::AsyncResultPtr&);
    
private:

    bool esVisible(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_esVisible(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void cogerCaja()
    {
        cogerCaja(0);
    }
    void cogerCaja(const ::Ice::Context& __ctx)
    {
        cogerCaja(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_cogerCaja(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_cogerCaja(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_cogerCaja(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_cogerCaja(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_cogerCaja(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_cogerCaja(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_cogerCaja(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_cogerCaja(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_cogerCaja()
    {
        return begin_cogerCaja(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_cogerCaja(const ::Ice::Context& __ctx)
    {
        return begin_cogerCaja(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_cogerCaja(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cogerCaja(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cogerCaja(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cogerCaja(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cogerCaja(const ::RoboCompIrObjetivo::Callback_IrObjetivo_cogerCajaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cogerCaja(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cogerCaja(const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_cogerCajaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cogerCaja(&__ctx, __del, __cookie);
    }

    void end_cogerCaja(const ::Ice::AsyncResultPtr&);
    
private:

    void cogerCaja(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_cogerCaja(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void soltarCaja()
    {
        soltarCaja(0);
    }
    void soltarCaja(const ::Ice::Context& __ctx)
    {
        soltarCaja(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_soltarCaja(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_soltarCaja(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_soltarCaja(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_soltarCaja(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_soltarCaja(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_soltarCaja(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_soltarCaja(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_soltarCaja(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_soltarCaja()
    {
        return begin_soltarCaja(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_soltarCaja(const ::Ice::Context& __ctx)
    {
        return begin_soltarCaja(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_soltarCaja(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_soltarCaja(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_soltarCaja(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_soltarCaja(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_soltarCaja(const ::RoboCompIrObjetivo::Callback_IrObjetivo_soltarCajaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_soltarCaja(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_soltarCaja(const ::Ice::Context& __ctx, const ::RoboCompIrObjetivo::Callback_IrObjetivo_soltarCajaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_soltarCaja(&__ctx, __del, __cookie);
    }

    void end_soltarCaja(const ::Ice::AsyncResultPtr&);
    
private:

    void soltarCaja(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_soltarCaja(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_secure(bool __secure) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_twoway() const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_oneway() const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_batchOneway() const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_datagram() const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_batchDatagram() const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_compress(bool __compress) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_timeout(int __timeout) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<IrObjetivo> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<IrObjetivo*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompIrObjetivo
{

class IrObjetivo : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Float getDistancia(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool esVisible(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void cogerCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void soltarCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompIrObjetivo
{

class IrObjetivo : virtual public ::IceDelegate::RoboCompIrObjetivo::IrObjetivo,
                   virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Float getDistancia(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool esVisible(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void cogerCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void soltarCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompIrObjetivo
{

class IrObjetivo : virtual public ::IceDelegate::RoboCompIrObjetivo::IrObjetivo,
                   virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void stop(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Float getDistancia(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool esVisible(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void cogerCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void soltarCaja(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompIrObjetivo
{

class IrObjetivo : virtual public ::Ice::Object
{
public:

    typedef IrObjetivoPrx ProxyType;
    typedef IrObjetivoPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void go(::Ice::Float, ::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___go(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void turn(::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___turn(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void stop(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___stop(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Float getDistancia(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getDistancia(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool esVisible(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___esVisible(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void cogerCaja(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___cogerCaja(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void soltarCaja(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___soltarCaja(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const IrObjetivo& l, const IrObjetivo& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const IrObjetivo& l, const IrObjetivo& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompIrObjetivo
{

template<class T>
class CallbackNC_IrObjetivo_go : public Callback_IrObjetivo_go_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_IrObjetivo_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_go<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_go<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_go : public Callback_IrObjetivo_go_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_IrObjetivo_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_goPtr
newCallback_IrObjetivo_go(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_turn : public Callback_IrObjetivo_turn_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_IrObjetivo_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_turn<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_turn<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_turn : public Callback_IrObjetivo_turn_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_IrObjetivo_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_turnPtr
newCallback_IrObjetivo_turn(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_stop : public Callback_IrObjetivo_stop_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_IrObjetivo_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_stop<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_stop<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_stop<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_stop : public Callback_IrObjetivo_stop_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_IrObjetivo_stop(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_stop<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_stop<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_stopPtr
newCallback_IrObjetivo_stop(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_stop<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_getDistancia : public Callback_IrObjetivo_getDistancia_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Float);

    CallbackNC_IrObjetivo_getDistancia(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
        ::Ice::Float __ret;
        try
        {
            __ret = __proxy->end_getDistancia(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_IrObjetivo_getDistanciaPtr
newCallback_IrObjetivo_getDistancia(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_getDistancia<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_getDistanciaPtr
newCallback_IrObjetivo_getDistancia(T* instance, void (T::*cb)(::Ice::Float), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_getDistancia<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_getDistancia : public Callback_IrObjetivo_getDistancia_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Float, const CT&);

    Callback_IrObjetivo_getDistancia(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
        ::Ice::Float __ret;
        try
        {
            __ret = __proxy->end_getDistancia(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_IrObjetivo_getDistanciaPtr
newCallback_IrObjetivo_getDistancia(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_getDistancia<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_getDistanciaPtr
newCallback_IrObjetivo_getDistancia(T* instance, void (T::*cb)(::Ice::Float, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_getDistancia<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_esVisible : public Callback_IrObjetivo_esVisible_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_IrObjetivo_esVisible(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_esVisible(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_IrObjetivo_esVisiblePtr
newCallback_IrObjetivo_esVisible(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_esVisible<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_esVisiblePtr
newCallback_IrObjetivo_esVisible(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_esVisible<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_esVisible : public Callback_IrObjetivo_esVisible_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_IrObjetivo_esVisible(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompIrObjetivo::IrObjetivoPrx __proxy = ::RoboCompIrObjetivo::IrObjetivoPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_esVisible(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_IrObjetivo_esVisiblePtr
newCallback_IrObjetivo_esVisible(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_esVisible<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_esVisiblePtr
newCallback_IrObjetivo_esVisible(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_esVisible<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_cogerCaja : public Callback_IrObjetivo_cogerCaja_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_IrObjetivo_cogerCaja(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_cogerCaja<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_cogerCaja<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_cogerCaja<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_cogerCaja<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_cogerCaja : public Callback_IrObjetivo_cogerCaja_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_IrObjetivo_cogerCaja(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_cogerCaja<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_cogerCaja<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_cogerCaja<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_cogerCajaPtr
newCallback_IrObjetivo_cogerCaja(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_cogerCaja<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_IrObjetivo_soltarCaja : public Callback_IrObjetivo_soltarCaja_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_IrObjetivo_soltarCaja(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_soltarCaja<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_soltarCaja<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_soltarCaja<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IrObjetivo_soltarCaja<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_IrObjetivo_soltarCaja : public Callback_IrObjetivo_soltarCaja_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_IrObjetivo_soltarCaja(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_soltarCaja<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_soltarCaja<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_soltarCaja<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IrObjetivo_soltarCajaPtr
newCallback_IrObjetivo_soltarCaja(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IrObjetivo_soltarCaja<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
